### ISSUE TITLE
Buying / Kickstarter possible?

### ISSUE THREAD

**Issue by mickeyl** [davidgfnet/wifi_display#10]
This is a great project, David. I could imagine a lot of people would be interested in having such a thing, alas not all of us are equipped with the necessary soldering skills. Do you have any interest in selling these devices or even launching a KickStarter project for commercializing this endeavor?

I've been looking for off-the-shelve programmable E-Ink gadgets in various sizes, but you either get only parts (which you then have to reverse engineer like you did) or cloud-based massively overpriced solutions.

**Comment by davidgfnet** [comment]
I've thought that already but it is quite complicated to start selling something like this as you can probably imagine. Companies will run some batch orders like this, but obviously you need to have like at least 1k units to make it "doable" at a reasonable cost. Also that will involve some nights flashing firmwares and doing some testing myself. Then shipping stuff over the world. Doable yeah, but a heck of work.
Would be nice if there were some intermediate companies that would do all of this for you and you could split profit some way author/builder. I guess the way to go would be to know someone in a fab in China, but it's not exactly an easy side job :D 
Thanks for the interest though :) There's lots of kindle 6 inch screens out there and it's quite easy and cheap to build a clone using them, if you feel brave ;)
