### ISSUE TITLE
Power supply

### ISSUE THREAD

**Issue by worried-networking** [davidgfnet/wifi_display#8]
Hi,

I'm not so familiar with electronics, can you please tell me if this module is enough to power the WifiDisplay — http://www.aliexpress.com/item/3-3-V600mA-isolating-switch-power-supply-module-board-Built-in-module-power-supply-AC-DC/32562744903.html? If not, can you please recommend one? I'd like to attach the display to a wall and forget about it.

**Comment by X-Ryl669** [comment]
Use any AC to USB plug (you should have plenty in your home already). It's very likely your ESP8266 is already using a microusb plug anyway.
The easiest method to "forget about it" is to follow the instructions in my fork (minimal soldering required, simplified software, no battery).

**Comment by worried-networking** [comment]
@X-Ryl669 thank you, I'll take a look.
